server {
    listen 8084;
    server_name localhost;
    charset urf-8;
    # 开启解压缩静态文件
	gzip_static on;

    # 关闭版本信息
    server_tokens off;

    # nginx日志配置
    #accss_log /var/log/nginx/access.log;
    #error_log /var/log/nginx/error.log;

        # 前端静态资源配置
        location / {
            root /home/vue/dist;
            try_files $uri $uri/ /index.html;
            index index.html index.htm;
        }

        # 代理到后端的服务
        location /dev-api/ {
            # rewrite ^/dev-api/(.*)$ /$1 break;
            proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # 如果是在docker中运行，需要使用host.docker.internal访问宿主机
            proxy_pass http://host.docker.internal:8086/;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }

}

