# 设置nginx的工作用户为超级管理员
#user root;
worker_processes  1;

events {
    worker_connections  2048;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    # 优化大文件传输效率，必须在sendfile on设置下才有效
    tcp_nopush    on;
    keepalive_timeout  65;

    # 隐藏nginx版本信息
    server_tokens off;

    # 设置上传文件大小上
    client_max_body_size 500m;

    gzip on;
    
    gzip_types text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php application/javascript application/json
    gzip_comp_level 6;

    # 引入自定义的配置nginx_dev.conf
    include /etc/nginx/conf.d/*.conf;
}
